use azure-publishersettings-credentials to set service subscription
jenkinsci/azure-slave-plugin pull request #13
Opened 2015-08-05 13:42 UTC by ndeloof

I've released [azure-publishersettings-credentials](https://github.com/jenkinsci/azure-publishersettings-credentials-plugin) plugin which I'm using in another (proprietary) plugin to interact with Azure to manage service subscription using Jenkins Credentials API.

This PR handle data migration so azure-slave plugin do use the same credential store without requirement to reconfigure jenkins.

2015-08-05 14:11 UTC, ndeloof commented
@reviewbybees

2015-08-05 14:12 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2015-08-05 14:24 UTC, stephenc commented
:bee:

2015-08-10 09:32 UTC, ndeloof commented
@reviewbybees done
@snallami can you please consider this PR ? Main idea is for users to rely on publisher settings file they can download from azure (http://go.microsoft.com/fwlink/?LinkId=254432)

2015-08-13 18:37 UTC, snallami commented
I will take a look and get back

2015-09-04 09:14 UTC, oleg-nenashev commented on pom.xml
> +			<dependency>
wrong tabs

2015-09-04 09:15 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureCloud.java
> +	public AzureCloud(String id, String credentialsId,
The plugin version should be changed to 0.4.0 IMO

2015-09-04 09:15 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureCloud.java
> +	public String getCredentialsId() {
add <code>@CheckForNull</code>

2015-09-04 09:16 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureCloud.java
> +			credentialsId = UUID.randomUUID().toString();
Probably the ID could have some info, e.g. "azure-cloud-migrated-UUID"

2015-09-04 09:17 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureCloud.java
> +
Much code formatting changes below :(

2015-09-04 09:18 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureCloud.java
> +	public AzurePublisherSettings getCredentials() {
<code>@CheckForNull</code>

2015-09-04 09:18 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureCloud.java
> +		}
Ohh, pretty formatting above :)

2015-09-04 09:19 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureManagementServiceDelegate.java
> +			String subscriptionID = credentials.getSubscriptionId();
Missing null check

2015-09-04 09:19 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureManagementServiceDelegate.java
> +		Configuration config = ServiceDelegateHelper.loadConfiguration(credentials.getSubscriptionId(),
Missing null check

2015-09-04 09:19 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureManagementServiceDelegate.java
> +		AzurePublisherSettings credentials = azureCloud.getCredentials();
Missing null check

2015-09-04 09:20 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureSlaveTemplate.java
> +		final AzurePublisherSettings credentials = azureCloud.getCredentials();
Missing null check

2015-09-04 09:20 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureSlaveTemplate.java
> +		final AzurePublisherSettings credentials = azureCloud.getCredentials();
and there...

2015-09-04 09:21 UTC, oleg-nenashev commented
:bug: for missing null checks in the potentially null credentials

2015-09-04 09:34 UTC, ndeloof commented
@oleg-nenashev no credentials set on this plugin would be a non-sense (you can't access azure without credentials). I don't think a custom IllegalStateException wouldn't be much useful vs a plain NullPointerException. Blame jenkins not being able to make some attribute required.

2015-09-04 09:35 UTC, oleg-nenashev commented
I disagree. In many cases you can gracefully handle nulls (FormValidation, etc.). In other cases implying NPEs is also a bad approach.

2015-09-04 09:40 UTC, ndeloof commented on pom.xml
> +			<dependency>
original formatting is a odd mix between spaces and tabs

2015-09-04 09:53 UTC, ndeloof commented
fixed NullCheck as request (even I'm concerned by this sudden love for `@CheckForNull`)
@reviewbybees done
@snallami wdyt ?

2015-09-04 09:54 UTC, oleg-nenashev commented
@ndeloof 
You should not put <code>@reviewbybees done</code> till you get a bees after the bug

2015-09-04 09:56 UTC, ndeloof commented
I've fixed the bug you noticed, what else ?
Please note this could have been merged long time ago according to reviewbybees rules

2015-09-04 09:57 UTC, oleg-nenashev commented
> Please note this could have been merged long time ago according to reviewbybees rules

Then we were lucky. I don't understand how it affects the policy.

I still think that annotations are required in the API

2015-09-04 10:10 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureCloud.java
> +	public String getCredentialsId() {
This one still needs a check

2015-09-04 10:11 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureCloud.java
> +					slave.toComputer().connect(false).get();
toComputer() may return null if the node has been reconfigured and we still use an old instance

2015-09-04 10:12 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureCloud.java
> +			String response = AzureManagementServiceDelegate.verifyConfiguration(
Missing null check. Should return a form error IMO

2015-09-07 11:07 UTC, oleg-nenashev commented
keeping :bug: for null checks

2015-09-26 02:00 UTC, snallami commented
Thanks for pull request. I will be testing the changes on Oct 2nd and 3rd and update you.
Once again thank you for your contribution

2015-10-04 06:33 UTC, snallami commented
@ndeloof, Great contribution. Thank you.

Couple of observations
1) Getting NullPointerException for below scenario. Can we add some validation?

In global config, Add new cloud --> select "Microsoft Azure" --> Just directly click on "verify configuration" , seeing NullPointerException.

2) Azure credentials plugin is throwing below error if previous existing publishing settings file is specified while creating a new set of credentails.  
```
javax.servlet.ServletException: java.lang.IllegalArgumentException: Failed to instantiate class com.cloudbees.plugins.credentials.domains.DomainCredentials from {"domain":{"name":"","description":""},"credentials":[{"description":"perforce","id":"5b0c350b-9252-4087-84be-fd74c6f9f492","p4port":"perforce.corp.expertcity.com:1666","username":"buildeng","password":"ecbuild2","retry":"2","stapler-class":"org.jenkinsci.plugins.p4.credentials.P4PasswordImpl","$class":"org.jenkinsci.plugins.p4.credentials.P4PasswordImpl"},{"scope":"GLOBAL","":false,"file":"file2","description":"myAzure","id":"1892f171-c7c5-489d-8a43-ca1f359e8a44","stapler-class":"org.jenkinsci.plugins.azure.AzurePublisherSettings","$class":"org.jenkinsci.plugins.azure.AzurePublisherSettings"},{"scope":"GLOBAL","file":"file3","description":"mynewazure","id":"","stapler-class":"org.jenkinsci.plugins.azure.AzurePublisherSettings","$class":"org.jenkinsci.plugins.azure.AzurePublisherSettings"}]}
```

3) One Publish settings may contain multiple subscriptions , how are we handling it in credentials plugin?

I thought of logging bugs directly for #2 and #3 but got below error in JIRA
The value 'azure-publishersettings-credentials-plugin' does not exist for the field 'component'.

2015-10-05 06:27 UTC, ndeloof commented
1) I've added a check for credentials so user get a human-readable error message when credentials selection is invalid - Jenkins UI framework is missing _required_ support.

2) I can't reproduce this error uploading a publishsettings file I just downloaded from Azure portal. The error you get is strange as it involves perforce plugin, and I can't understand possible interaction here - will install to try to reproduce. 

3) I didn't know a Publishsettings file could include multiple subscriptions, I guess we can support this by adding a second level subscription selector.

2015-10-05 08:28 UTC, ndeloof commented
I can confirm a very strange FileUpload issue when creating a new credential item from the /credentials view. First credential is ok to register, but next one fails when using the same file to be uploaded.

Based on this issue + 3) I'm going to change publishersettings-credentials UI so it exposes the profile attribute as classic text inputs, then will investigate how to offer some ajax-based helper so user can upload his publihsettings file so it get parsed.

2015-10-05 10:54 UTC, ndeloof commented
Could you please try using development build https://jenkins.ci.cloudbees.com/job/plugins/job/azure-publishersettings-credentials-plugin/6/ ?

2015-10-05 11:44 UTC, oleg-nenashev commented
@ndeloof 
You've fixed only one null check issue referenced by me. What about other one?
Keeping :bug:

2016-02-08 23:51 UTC, ndeloof commented
@snallami I rebased on plugin HEAD.
I also created `azure-publishersettings-credentials-plugin` component in issue tracker, feel free to report detected issues.

2017-04-02 19:31 UTC, stephenc commented
@oleg-nenashev can you re-review the pr has been updated since your bug and sitting blocked for nearly 1 year now

2017-04-02 19:50 UTC, oleg-nenashev commented
@stephenc Maybe just because nobody pinged me that the comments got addressed. 1 year ago there was notifications for pushes.

2017-04-02 20:00 UTC, oleg-nenashev requested changes
The merge conflict needs to be resolved. The change itself seems to be acceptable to me. Binary compatibility breakage is IMHO justified (credentials support)

2017-04-02 20:00 UTC, oleg-nenashev commented on pom.xml
> +      	<version>0.1.51</version>
Would be better to depend on a plugin like Publish Over SSH to avoid binary compat issues

2017-04-02 20:00 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureManagementServiceDelegate.java
> +	public static List<String> verifyTemplate(AzurePublisherSettings credentials, String passPhrase,
Maybe `@Restricted()`. I doubt it is designed for the external use

2017-04-02 20:00 UTC, oleg-nenashev commented on src/main/java/com/microsoftopentechnologies/azure/AzureSlaveTemplate.java
>  		public ListBoxModel doFillVirtualMachineSizeItems(
Better to restrict stapler methods once you see them

2019-09-06 14:11 UTC, ndeloof commented
inactive, feel free to take over

2019-09-06 14:11 UTC, closed without merging